---

- name: Copy desktop wallpaper
  win_copy:
    src: files/DesktopWallpaper.jpg
    dest: C:\Users\Public\Pictures\DesktopWallpaper.jpg

- name: Copy bginfo configuration
  win_copy:
    src: files/bginfo.bgi
    dest: C:\Users\Public\bginfo.bgi

- name: ensure .NET Framework 4.8 requirement is satisfied for Chocolatey CLI v2.0.0+
  block:
  - name: install Chocolatey CLI v1.4.0
    win_chocolatey:
      name: 'chocolatey'
      state: present
      version: '1.4.0'
    ignore_errors: true

  - name: install Microsoft .NET Framework 4.8
    win_chocolatey:
      name: 'netfx-4.8'
      state: present
    register: reboot_for_netfx

  - name: Reboot the host to complete .NET Framework 4.8 install
    ansible.windows.win_reboot:
    when: reboot_for_netfx.rc !=0

  - name: install Chocolatey CLI v2.0.0+ when .NET Framework 4.8 dependency is met
    win_chocolatey:
      name: 'chocolatey'
      state: latest

# Note: Chocolatey packages should be minimized to avoid hitting the rate limit (only 1 outbound IP is used)
- name: Install utilities 
  win_chocolatey:
    name:
    - GoogleChrome
    - bginfo
    state: present
    ignore_checksums: true

# Note: to fix later
- name: Install elastic agent
  include_role:
    name: elastic-agent
  tags: never

- name: Configure bginfo as autorun
  win_regedit:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run'
    name: bginfo
    data: 'C:\ProgramData\chocolatey\bin\bginfo.exe c:\users\public\bginfo.bgi /silent /timer:0 /nolicprompt'

- name: Ensure 'Search' unpinned from the taskbar
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Search
    name: SearchboxTaskbarMode
    data: 0
    type: dword

- name: Ensure 'News and Interests' unpinned from the taskbar
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds
    name: EnableFeeds
    data: 0
    type: dword
    state: present

- name: Ensure 'People' unpinned from the taskbar
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\People
    name: PeopleBand
    data: 0
    type: dword

- name: Ensure 'Edge', 'Store' other built-in shortcuts unpinned from the taskbar
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband
    name: Favorites
    state: absent

- name: Hide Task View, Chat and Cortana, always show file extensions
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: "{{ item }}"
    data: 0
    type: dword
  loop:
    - ShowCortanaButton
    - ShowTaskViewButton
    - TaskbarDa
    - TaskbarMn
    - HideFileExt
